### ISSUE TITLE
Source of the data is not clear nor how it is kept up todate

### ISSUE THREAD

**Issue by seif** [IbrahimMohammed47/boycott-z#21]
The extension checks brands by using supabase however it is not clear to me nor users how this data ended up there and what is the source of the data.

Should we look into integrating with one of the tech4palestine sources? That would reduce the burden on us to manage the data and also is more transparent.

**Comment by IbrahimMohammed47** [comment]
This is why we have a "Proof" button

However, I recently made a small website, which tells the sources in FAQ section (which tech4palestine is one of):
boycott-z.com

But I'm still not referencing the website, because the popup design sucks.. I will add it after I have a good design

**Comment by seif** [comment]
thanks @IbrahimMohammed47 how does the data end up in supabase? are there some scripts or something that can be added to repository for people to contribute to? For example do add more tlds for specific companied as mentiond in #22 ?
